[package]
name = "cellulite"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "benchmarks","examples/*"]

[dependencies]
geo = "0.29.3"
geo-types = "0.7.15"
h3o = { version = "0.7.1", features = ["geo"] }
heed = "0.22.0"
ordered-float = "5.0.0"
roaring = "0.10.10"
thiserror = "2.0.12"

[dev-dependencies]
insta = "1.42.2"
tempfile = "3.19.1"
