[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
cellulite = { path = ".." }
tempfile = "3.19.1"
heed = "0.22.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
flate2 = "1.1.0"
